name: Update Rule List

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update China List
      run: |
        DATE_COMMENT="Updated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        curl -o china-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt
        sed -i "1s|^|# $DATE_COMMENT\n|" china-list.txt

    - name: Update Proxy List
      run: |
        DATE_COMMENT="Updated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        curl -o proxy-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt
        sed -i "1s|^|# $DATE_COMMENT\n|" proxy-list.txt

    - name: Update Reject List
      run: |
        DATE_COMMENT="Updated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        curl -o reject-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
        sed -i "1s|^|# $DATE_COMMENT\n|" reject-list.txt

    - name: Process China List
      run: |
        sed -i '2,$s/^full:/DOMAIN,/' china-list.txt
        sed -i '2,$s/^regexp:/URL-REGEX,/' china-list.txt
        sed -i '2,$s/^[^full|^regexp]/DOMAIN-SUFFIX,/'china-list.txt

    - name: Process Proxy List
      run: |
        sed -i '2,$s/^full:/DOMAIN,/' proxy-list.txt
        sed -i '2,$s/^regexp:/URL-REGEX,/' proxy-list.txt
        sed -i '2,$s/^[^full|^regexp]/DOMAIN-SUFFIX,/' proxy-list.txt

    - name: Process Reject List
      run: |
        sed -i '2,$s/^full:/DOMAIN,/' reject-list.txt
        sed -i '2,$s/^regexp:/URL-REGEX,/' reject-list.txt
        sed -i '2,$s/^[^full|^regexp]/DOMAIN-SUFFIX,/' reject-list.txt

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"

    - name: Commit and Push Changes
      run: |
        git add china-list.txt proxy-list.txt reject-list.txt
        git commit -m "Update Rule List"
        git push origin main
